services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
      target: app
    image: ghcr.io/archi-tektur/symfony-project-bootstrap:app-${VERSION:-2.0.0}
    environment:
      APP_ENV: "dev"
      APP_SECRET: "a9806d99cd5c1503d8af30c963c9411f"
      DATABASE_URL: "mysql://user:password@mariadb:3306/symfony-bootstrap"
  mariadb:
    image: 'mariadb:10.6'
    environment:
      MYSQL_ROOT_PASSWORD: "password"
      MYSQL_DATABASE: "symfony-bootstrap"
      MYSQL_USER: "user"
      MYSQL_PASSWORD: "password"
